name: Add labels to PR
run-name: Add labels to ${{ github.event.pull_request.head.ref }}

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches: [develop, main]

permissions:
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Add labels to PR
      uses: srvaroa/labeler@v1.8.0
      with:
        config_path: .github/labeler-config.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}