name: Run tests
run-name: Run tests for ${{ github.event.pull_request.head.ref }}

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - develop

jobs:
  test:
    runs-on: [ self-hosted, linux, x64 ]

    steps:
      - uses: actions/checkout@v3

      - name: Read Flutter version to use
        uses: kuhnroyal/flutter-fvm-config-action@v1
        id: fvm_config

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm_config.outputs.FLUTTER_VERSION }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm_config.outputs.FLUTTER_VERSION }}

      - name: Download dependencies
        run: fvm flutter pub get

      - name: Analyze
        run: fvm flutter analyze

      - name: Test
        run:  fvm flutter test