name: Run tests
run-name: Run tests for ${{ github.event.pull_request.head.ref }}

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Read Flutter version to use
        uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
        with:
          path: '.fvmrc'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm_config.outputs.FLUTTER_VERSION }}

      - name: Download dependencies
        run: fvm flutter pub get

      - name: Analyze
        run: fvm flutter analyze

      - name: Test
        run:  fvm flutter test